# Generated by Django 5.1.1 on 2024-10-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_remove_book_description_alter_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='text'),
            preserve_default=False,
        ),
    ]
